config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  get '/posts/new' => 'posts#new'
  post '/posts' => 'posts#create', as: 'posts'
  get '/posts/:id' => 'posts#show', as: 'post'

  get '/users/new' => 'users#new'
  post '/users' => 'users#create', as: 'users'
  get '/users/:id' => 'users#show', as: 'user'

  get '/games/new' => 'games#new'
  post '/games' => 'games#create', as: 'games'
  get '/games/:id' => 'games#show', as: 'game'

  post "/games/1" => 'games#comment', as: 'game_comments'

  # get '/games/:id/game_comments' => 'game_comments#index'
  # get '/game_comments/new' => 'game_comments#new'
  # post '/games/:id/game_comments' => 'game_comments#create', as: 'game_comments'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create', as: 'logins'
  delete '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :game_comments

  validates :name, :platform, :esrb_rating, presence: true
end

app/models/game_comment.rb
class GameComment < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :comment, presence: true
  validates :comment, length: {in: 1..200}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments

  validates :title, :body, presence: true
  validates :title, length: {minimum: 3}
  validates :body, length: {in: 5..300}
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
  validates :comment, length: {in: 1..200}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :games
  has_many :post_comments
  has_many :game_comments

  validates :username, :email, :password, presence: true
  validates :username, :email, uniqueness: true
  validates :password, length: {minimum: 6}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/game_comments_controller.rb
# class GameCommentsController < ApplicationController
#   # def new
#   #   @game_comment = GameComment.new
#   # end
#
#   def index
#     game = Game.find(params[:id])
#     @game_comments = GameComment.all.where(game_id: game)
#     # debugger
#   end
#
#   def create
#     if logged_in?
#       @game = Game.find(1)
#       @game_comment = GameComment.new(comment: game_comments_params, user_id: current_user.id, game_id: @game)
#       # debugger
#       if @game_comment.save
#         redirect_to @game
#       else
#         redirect_to @game
#       end
#     else
#       flash[:danger] = "You must be logged in to comment."
#       redirect_to root
#     end
#   end
#
#   private
#
#     def game_comments_params
#       params.require(:game_comment).permit(:comment)
#     end
# end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = Game.find(params[:id])
    @game_comments = GameComment.where(game_id: @game).all
  end

  def new
    @game = Game.new
  end

  def create
    if logged_in?
      @game = current_user.games.new(game_params)
      if @game.save
        redirect_to @game
      else
        render 'new'
      end
    end
  end

  def comment
    if logged_in?
      @game = Game.find(1)
      @game_comment = GameComment.new(comment: game_comments_params, user_id: current_user.id, game_id: @game)
      if @game_comment.save
        flash.now[:notice] = "Post successful!"
        redirect_to @game
      else
        flash[:danger] = "Your comment was not posted."
      end
    else
      flash.now[:notice] = "You must be logged in to post a comment."
      redirect_to root_path
    end
  end

  private

    def game_params
      params.require(:game).permit(:name, :platform, :esrb_rating, :genre, :score)
    end

    def game_comments_params
      params.require(:game_comment).permit(:comment)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @post_comments = PostComment.where(post_id: @post).all
  end

  def index
    @posts = Post.all
    @games = Game.all
  end

  def new
    @post = Post.new
  end

  def create
    if logged_in?
      @post = current_user.posts.new(post_params)
      if @post.save
        redirect_to @post
      else
        render 'new'
      end
    end
  end

  private

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      redirect_to @user
    else
      flash.now[:danger] = "Invalid email/password. Please try again."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/game_comments/new.html.erb
<%= react_component 'CommentForm' %>

app/views/games/_game_errors.html.erb
<% if @game.errors.any? %>
  <div class="alert">
    <strong>The form contains <%= pluralize(@game.errors.count, "error") %>.</strong>
  </div>

  <% @game.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

app/views/games/new.html.erb
<div class="new-game-form">
  <h2>Add Game</h2>

  <%= form_for @game do |f| %>
    <%= render 'game_errors' %>

    <%= f.label :name %><br>
    <%= f.text_field :name %><br><br>

    <%= f.label :platform %><br>
    <%= f.text_field :platform %><br><br>

    <%= f.label :esrb_rating %><br>
    <%= f.text_field :esrb_rating %><br><br>

    <%= f.label :genre %><br>
    <%= f.text_field :genre %><br><br>

    <%= f.label :score %><br>
    <%= f.text_field :score %><br><br>

    <%= f.submit 'Add' %>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="game-show-page">
  <h2><%= @game.name %></h2>

  <p><strong>Platform:</strong> <%= @game.platform %></p>
  <p><strong>ESRB Rating:</strong> <%= @game.esrb_rating %></p>
  <p><strong>Genre:</strong> <%= @game.genre %></p>
  <p><strong>User Score:</strong> <%= @game.score %>/10</p>

  <ul id="game-comments">
    <h3>Comments</h3>
    <% @game_comments.each do |comment| %>
      <li><%= comment.comment %></li>
    <% end %>
  </ul>
  <%= react_component 'ShowPage' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dojo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class='nav-bar'>
      <h1>Dojo</h1>
        | <%= link_to 'Home', root_path %> |
      <% if logged_in? %>
      <h3>Welcome, <%= current_user.username %><h3>
        | <%= link_to 'Create Post', posts_new_path %> |
        <%= link_to 'Add Game', games_new_path %> |
        <%= link_to 'Profile', user_path(current_user) %> |
        <%= link_to 'Logout', logout_path, method: 'delete' %> |
      <% else %>
        <%= link_to 'Create Account', users_new_path %> |
        <%= link_to 'Login', login_path %>
      <% end %>

    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_post_errors.html.erb
<% if @post.errors.any? %>
  <div class="alert">
    <strong>The form contains <%= pluralize(@post.errors.count, "error") %>.</strong>
  </div>

  <% @post.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<div class="posts-container">
<h2>All Posts</h2>
<% @posts.each do |post| %>
  <tr>
    <td><p><strong><%= link_to post.title, post_path(post) %></strong></td>
  </tr>
<% end %>
</div>

<div class="games-container">
<h2>All Games</h2>
<% @games.each do |game| %>
  <tr>
    <td><p><strong><%= link_to game.name, game_path(game) %></strong></p></td>
  </tr>
<% end %>
</div>

app/views/posts/new.html.erb
<div class="new-post-form">
  <h2>Create Post</h2>

  <%= form_for @post do |f| %>
    <%= render 'post_errors' %>

    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>

    <%= f.label :body %><br>
    <%= f.text_area :body %><br><br>

    <%= f.submit 'Post' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="post-show-page">
  <h2><%= @post.title %></h2>

  <p><%= @post.body %></p>

  <ul id="post-comments">
    <h3>Comments</h3>
    <% @post_comments.each do |comment| %>
      <li><%= comment.comment %></li>
    <% end %>
  </ul>
  <%= react_component 'ShowPage' %>
</div>

app/views/users/_user_errors.html.erb
<% if @user.errors.any? %>
  <div class="alert">
    <strong>The form contains <%= pluralize(@user.errors.count, "error") %>.</strong>
  </div>

  <% @user.errors.full_messages.each do |message| %>
    <p><%= message %><p>
  <% end %>
<% end %>

app/views/users/new.html.erb
<div class="account-form">
  <h2>Create Account</h2>

  <%= form_for @user, url: users_path do |f| %>
    <%= render 'user_errors' %>

    <%= f.label :username %><br>
    <%= f.text_field :username %><br><br>

    <%= f.label :email %><br>
    <%= f.email_field :email %><br><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br><br>

    <%= f.submit "Create Account" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-show-page">
  <h2>Hiya, @user.username</h2>
  <%= @user.email %>
  
  <% @user.posts.each do |post| %>
    <p><%= post.title %></p>
  <% end %>

  <% @user.games.each do |game| %>
    <p><%= game.name %>, <%= game.platform %></p>
  <% end %>
</div>